config/routes.rb
MovieEcommStore::Application.routes.draw do
  root :to => 'store#index', :as => 'home', :via => :get
  match '/products' => 'movieproducts#index', :as => 'all_movieproducts', :via => :get
  match '/products/new-releases' => 'movieproducts#newest_products', :as => 'new_products', :via => :get
  match '/products/updated-products' => 'movieproducts#updated_products', :as => 'updated_products', :via => :get
  match '/products/search-results' => 'store#search_results', :as => 'search_results', :via => :get
  match '/products/:id' => 'movieproducts#show', :as => 'movieproduct', :via => :get
  match '/category/:name/products' => 'categories#index', :as => 'products_for_category', :via => :get
  match '/store/add-to-cart/:id' => 'store#add_to_cart', :as => 'add_to_cart', :via => :post
  match '/store/remove-from-cart/:id' => 'store#remove_from_cart', :as => 'remove_from_cart', :via => :post
  match '/store/reset-cart' => 'store#reset_cart', :as => 'reset_cart', :via => :post
  match '/store/cart' => 'store#view_cart', :as => 'view_cart', :via => :get
  match '/store/checkout' => 'store#checkout', :as => 'checkout', :via => :get
  match '/store' => 'store#place_order', :as => 'place_order', :via => :post
  match '/store/:id/:permalink' => 'store#static_page', :as => 'static_page', :via => :get

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/views/shared/_cartbutton.html.erb
<% if movieproduct.stock_quantity > 0 %>
    <% if session[:shopping_cart].include?(movieproduct.id) %>
        <p class="cartbutton"><%= link_to "Remove from Cart", remove_from_cart_path(movieproduct.id), :method => :post, :class => 'btn btn-primary' %></p>
    <% else %>
        <p class="cartbutton"><%= link_to "Add to Cart", add_to_cart_path(movieproduct.id), :method => :post, :class => 'btn btn-primary' %></p>
    <% end %>
<% else %>
    <p class="cartbutton"><button type="button" class="btn btn-primary" disabled="disabled">Add to Cart</button></p>
<% end %>

app/views/shared/_cartlist.html.erb
<li><%= link_to cartlist.movie.title, movieproduct_path(cartlist.id) %></li>

app/views/shared/_featureproduct.html.erb
<div class="col-lg-4">
  <%= image_tag featuredproduct.image_path, :class => 'img-thumbnail', :alt => 'Featured Product' %>
  <h2><%= featuredproduct.movie.title %></h2>
  <p class="description"><%= featuredproduct.description%></p>
  <p><%= link_to "View Details", movieproduct_path(featuredproduct.id), :class => 'btn btn-default' %></p>
</div>

app/views/shared/_hotproduct.html.erb
<% if hotproduct_counter % 2 != 0 %>
    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading"><%= hotproduct.movie.title %><span class="text-muted"><%= hotproduct.created_at.strftime('%b %d, %Y') %></span></h2>
        <p class="lead"><%= hotproduct.description %></p>
        <p><%= link_to "View Details", movieproduct_path(hotproduct.id), :class => 'btn btn-default' %></p>
      </div>
      <div class="col-md-5">
        <%= image_tag hotproduct.image_path, :class => 'featurette-image img-responsive', :width => '500', :alt => 'Popular New Product' %>
      </div>
    </div>

    <hr class="featurette-divider"/>
<% else %>
    <div class="row featurette">
      <div class="col-md-5">
        <%= image_tag hotproduct.image_path, :class => 'featurette-image img-responsive', :width => '500', :alt => 'Popular New Product' %>
      </div>
      <div class="col-md-7">
        <h2 class="featurette-heading"><%= hotproduct.movie.title %><span class="text-muted"><%= hotproduct.created_at.strftime('%b %d, %Y') %></span></h2>
        <p class="lead"><%= hotproduct.description %></p>
        <p><%= link_to "View Details", movieproduct_path(hotproduct.id), :class => 'btn btn-default' %></p>
      </div>
    </div>

    <hr class="featurette-divider"/>
<% end %>

app/views/shared/_search.html.erb
<div class="col-xs-3"></div>
<%= form_tag search_results_path, {:method => :get, :class => 'form-horizontal', 'role' => 'form'} do %>
    <div class="form-group">
      <%= label_tag 'keywords', 'Search', :class => 'col-xs-1 control-label' %>
      <div class="col-xs-5">
        <%= text_field_tag 'keywords', nil, {:class => 'form-control', :placeholder => 'Search'} %>
      </div>
      <div class="col-xs-2">
        <%= select_tag 'category', options_from_collection_for_select(Category.all, :id, :name), {:class => 'form-control', :prompt => 'All'} %>
      </div>
      <%= button_tag 'Search', :class => 'btn btn-primary' %>
    </div>
<% end %>