config/routes.rb
MovieEcommStore::Application.routes.draw do
  root :to => 'store#index', :as => 'home', :via => :get
  match '/products' => 'movieproducts#index', :as => 'all_movieproducts', :via => :get
  match '/products/new-releases' => 'movieproducts#newest_products', :as => 'new_products', :via => :get
  match '/products/updated-products' => 'movieproducts#updated_products', :as => 'updated_products', :via => :get
  match '/products/search-results' => 'store#search_results', :as => 'search_results', :via => :get
  match '/products/:id' => 'movieproducts#show', :as => 'movieproduct', :via => :get
  match '/category/:name/products' => 'categories#index', :as => 'products_for_category', :via => :get
  match '/store/add-to-cart/:id' => 'store#add_to_cart', :as => 'add_to_cart', :via => :post
  match '/store/remove-from-cart/:id' => 'store#remove_from_cart', :as => 'remove_from_cart', :via => :post
  match '/store/reset-cart' => 'store#reset_cart', :as => 'reset_cart', :via => :post
  match '/store/cart' => 'store#view_cart', :as => 'view_cart', :via => :get
  match '/store/checkout' => 'store#checkout', :as => 'checkout', :via => :get
  match '/store' => 'store#place_order', :as => 'place_order', :via => :post
  match '/store/:id/:permalink' => 'store#static_page', :as => 'static_page', :via => :get

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @random_products = Movieproduct.three_random_products
    @newest_products = Movieproduct.order('created_at DESC').limit(3)
  end

  def static_page
    if params.has_key?(:id) && params.has_key?(:permalink)
      page_id = params[:id]
      @page_content = Page.find(page_id)
    else
      redirect_to root_path
    end
  end

  def search_results
    if params.has_key?(:keywords) && params.has_key?(:category)
      keywords = params[:keywords]
      product_category = params[:category]

      #possible problem with paginating because you can only access search results with post
      if product_category.empty?
        @movieproduct_results = Movieproduct.joins(:movie).where(["movies.title LIKE ? OR movieproducts.description LIKE ?", "%#{keywords}%", "%#{keywords}%"]).order('movies.title').page(params[:page]).per(15)
      else
        @movieproduct_results = Movieproduct.joins(:movie).where("movieproducts.category_id = #{product_category}").where(["movies.title LIKE ? OR movieproducts.description LIKE ?", "%#{keywords}%", "%#{keywords}%"]).order('movies.title').page(params[:page]).per(15)
      end
    else
      redirect_to root_path
    end
  end

  def add_to_cart
    id = params[:id].to_i
    session[:shopping_cart] << id unless session[:shopping_cart].include?(id)
    flash[:product_added] = '1 Movie Product added to your Cart'
    redirect_to :action => :view_cart
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:shopping_cart].delete(id)
    flash[:product_removed] = '1 Movie Product removed from your Cart'
    redirect_to :action => :view_cart
  end

  def reset_cart
    session[:shopping_cart] = nil
    redirect_to :action => :index
  end

  def view_cart
  end

  def checkout
    @customer = Customer.new
    @provinces = Province.order(:name)
  end

  def place_order
    #order_total = 0.0
    #error_msg = 'A database error occurred and your order was not submitted, please try again.'

    @customer = Customer.new(params[:customer])
    @customer.save

    @order = @customer.orders.build

    @order.gst_rate = @customer.province.gst
    #gst = @customer.province.gst
    @order.pst_rate = @customer.province.pst
    #pst = @customer.province.pst
    @order.hst_rate = @customer.province.hst
    #hst = @customer.province.hst
    @order.status = 'new'

    @order.save

    #if @order.errors.any?
    #  flash.now[:error] = error_msg
    #  render :action => :checkout
    #end

    session[:shopping_cart].each do |id|
      movie_product = Movieproduct.find(id)

      movie_product_order = @order.movieproductorders.build
      movie_product_order.movieproduct = movie_product
      movie_product_order.price = movie_product.price
      movie_product_order.quantity = movie_product.stock_quantity

      #order_total += movie_product_order.price

      movie_product.stock_quantity -= 1

      movie_product.save
      movie_product_order.save

      #if movie_product.errors.any? || movie_product_order.errors.any?
      #  flash.now[:error] = error_msg
      #  render :action => :checkout
      #end
    end

    #order_total += (order_total * pst) + (order_total * gst) + (order_total * hst)

    session[:shopping_cart] = nil
    flash[:completed_order] = "Thank You for your order, it is being processed and will be shipped very soon"
    redirect_to :action => :index
  end

  def test
    @customer = Customer.new(params[:customer])
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/store/checkout.html.erb
<div class="page-header">
  <h1>Checkout</h1>
</div>
<%= form_for @customer, :url => place_order_path(@customer) do |f| %>
    <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, :class => 'form-control', :placeholder => 'First Name' %>
    </div>
    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, :class => 'form-control', :placeholder => 'Last Name' %>
    </div>
    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, :class => 'form-control', :placeholder => '11-111 Some St.' %>
    </div>
    <div class="form-group">
      <%= f.label :city %>
      <%= f.text_field :city, :class => 'form-control', :placeholder => 'City' %>
    </div>
    <div class="form-group">
      <%= f.label :province_id %><br />
      <%= f.collection_select :province_id, @provinces, :id, :name, {}, { :class => 'form-control' } %>
    </div>
    <div class="form-group">
      <%= f.label :country %>
      <%= f.country_select :country, ['Canada', 'United States'], {}, {:class => 'form-control'} %>
    </div>
    <div class="form-group">
      <%= f.label :postal_code %>
      <%= f.text_field :postal_code, :class => 'form-control', :placeholder => 'A1A 1A1' %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, :class => 'form-control', :placeholder => 'email@example.com' %>
    </div>
    <hr/>
    <p>
        <%= f.submit 'Place Order', :class => 'btn btn-primary btn-lg' %>&nbsp;&nbsp;&nbsp;<%= link_to "Continue Shopping", root_path, :class => 'btn btn-primary btn-lg' %>
    </p>
<% end %>
<footer>
  <p class="pull-right"><a href="#">Back to top</a></p>
  <p>&copy; 2013 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
</footer>

app/views/store/index.html.erb
<% if flash[:completed_order] %>
    <p class="alert alert-success"><%= flash[:completed_order] %></p>
<% end %>
<div class="jumbotron">
  <h1>Welcome to</h1>
  <h1>Take-One Movie Goods Co.</h1>
  <p>We offer a large selection of movies and movie posters. Feel free to browse and check out all our products.</p>
  <p>You can also check out our latest products and products for movies that were release this year, or search for exactly what you want.</p>
  <p>You can buy anything you see either online, or you can visit one of our three Winnipeg locations.</p>
  <p>If you want to know more about our company or have any questions check out our About and Contact pages.</p>
</div>


<div class="page-header">
  <h1>Featured Products</h1>
</div>

<div class="container marketing">

  <div class="row">
    <%= render :partial => 'shared/featureproduct', :collection => @random_products, :as => 'featuredproduct' %>
  </div><!-- /.row -->

  <div class="page-header">
    <h1>New &amp; Hot Products</h1>
  </div>

  <%= render :partial => 'shared/hotproduct', :collection => @newest_products, :as => 'hotproduct' %>

  <footer>
    <p class="pull-right"><a href="#">Back to top</a></p>
    <p>&copy; 2013 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
</div>

app/views/store/search_results.html.erb
<div class="page-header">
  <h1>Search Results</h1>
</div>
<% if @movieproduct_results.empty? %>
    <div class="alert alert-danger">Sorry, your search for '<%= params[:keywords] %>' returned no results.</div>
<% end %>
<%= render @movieproduct_results %>
<%= paginate @movieproduct_results %>
<footer>
  <p class="pull-right"><a href="#">Back to top</a></p>
  <p>&copy; 2013 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
</footer>

app/views/store/static_page.html.erb
<div class="page-header">
  <h1><%= @page_content.title %></h1>
</div>
<p class="lead"><%= @page_content.content %></p>
<footer>
  <p class="pull-right"><a href="#">Back to top</a></p>
  <p>&copy; 2013 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
</footer>

app/views/store/test.html.erb
<h1>Testing</h1>
<%= debug session %>
<%= debug @customer %>

app/views/store/view_cart.html.erb
<div class="page-header">
  <h1>Your Cart</h1>
</div>
<% if session[:shopping_cart].empty? %>
    <div class="alert alert-danger">You have no items in your shopping cart.</div>
<% else %>
  <% if flash[:product_added] %>
    <div class="alert alert-success"><%= flash[:product_added] %></div>
  <% elsif flash[:product_removed] %>
    <div class="alert alert-danger"><%= flash[:product_removed] %></div>
  <% end %>
  <table class="table">
    <thead>
        <tr>
          <th></th>
          <th>Product</th>
          <th class="text-center">Quantity</th>
          <th class="text-center">Price</th>
        </tr>
    </thead>
    <tbody>
        <% @cart_products.each do |movieproduct| %>
            <tr>
              <td>
                <% if movieproduct.image_path %>
                    <%= image_tag movieproduct.image_path, :width => '75', :alt => 'image', :class => 'media-object' %>
                <% end %>
              </td>
              <td><%= "#{movieproduct.movie.title} (#{movieproduct.category.name})" %></td>
              <td class="text-center">1</td>
              <td class="text-right"><%= number_to_currency(movieproduct.price) %>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "Remove", remove_from_cart_path(movieproduct.id), :method => :post %></td>
            </tr>
        <% end %>
    </tbody>
    <tfoot>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td class="text-right">Subtotal: <%= number_to_currency(@cart_products.map{|cp| cp.price}.inject(:+)) %></td>
        </tr>
    </tfoot>
  </table>
  <p class="cartbutton text-right"><%= link_to "Checkout", checkout_path, :class => 'btn btn-primary btn-lg' %></p>
<% end %>
<footer>
  <p class="pull-right"><a href="#">Back to top</a></p>
  <p>&copy; 2013 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
</footer>