config/routes.rb
MovieEcommStore::Application.routes.draw do
  root :to => 'store#index', :as => 'home', :via => :get
  match '/products' => 'movieproducts#index', :as => 'all_movieproducts', :via => :get
  match '/products/new-releases' => 'movieproducts#newest_products', :as => 'new_products', :via => :get
  match '/products/updated-products' => 'movieproducts#updated_products', :as => 'updated_products', :via => :get
  match '/products/search-results' => 'store#search_results', :as => 'search_results', :via => :get
  match '/products/:id' => 'movieproducts#show', :as => 'movieproduct', :via => :get
  match '/category/:name/products' => 'categories#index', :as => 'products_for_category', :via => :get
  match '/store/add-to-cart/:id' => 'store#add_to_cart', :as => 'add_to_cart', :via => :post
  match '/store/remove-from-cart/:id' => 'store#remove_from_cart', :as => 'remove_from_cart', :via => :post
  match '/store/reset-cart' => 'store#reset_cart', :as => 'reset_cart', :via => :post
  match '/store/cart' => 'store#view_cart', :as => 'view_cart', :via => :get
  match '/store/checkout' => 'store#checkout', :as => 'checkout', :via => :get
  match '/store' => 'store#place_order', :as => 'place_order', :via => :post
  match '/store/:id/:permalink' => 'store#static_page', :as => 'static_page', :via => :get

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Take One Movie Goods</title>
      <%= stylesheet_link_tag    "application", :media => "all" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
    </head>
    <body>
        <!-- Fixed navbar -->
        <div class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to 'Take-One', root_path, :class => "navbar-brand" %>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Products <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'All Products', all_movieproducts_path %></li>
                    <li><%= link_to 'Blu-Rays', products_for_category_path(:name => 'Blu-Ray') %></li>
                    <li><%= link_to 'Posters', products_for_category_path(:name => 'Poster') %></li>
                  </ul>
                </li>
                <li><%= link_to 'New', new_products_path %></li>
                <li><%= link_to 'Updated', updated_products_path %></li>
                <li><a href="#contact">Bestsellers</a></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <%= render @pages %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= image_tag 'cart.png', :alt => 'cart' %>Cart <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <% if session[:shopping_cart].empty? %>
                        <li><a href="#">No Items</a></li>
                    <% else %>
                        <%= render :partial => 'shared/cartlist', :collection => @cart_products, :as => 'cartlist' %>
                    <% end %>
                    <li class="divider"></li>
                    <li><%= link_to 'View Cart', view_cart_path %></li>
                    <li><%= link_to 'Reset Cart', reset_cart_path, :method => :post %></li>
                  </ul>
                </li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </div>
        <div class="container">
          <%= render 'shared/search' %>
          <%= yield %>
        </div>
    </body>
</html>